from django.contrib import admin
from .models import Aguascalientes, BajaCalifornia, BajaCaliforniaSur, Campeche, Chiapas, Chihuahua, Coahuila, Colima, CiudadDeMexico, Durango, Guanajuato,Guerrero, Hidalgo, Jalisco, EstadoDeMexico, Michoacan, Morelos, Nayarit, NuevoLeon, Oaxaca, Puebla, Queretaro, QuintanaRoo, SanLuisPotosi, Sinaloa, Sonora, Tabasco, Tamaulipas, Tlaxcala, Veracruz, Yucatán, Zacatecas
# Register your models here.
admin.site.register(Aguascalientes)
admin.site.register(BajaCalifornia)
admin.site.register(BajaCaliforniaSur)
admin.site.register(Campeche)
admin.site.register(Chiapas)
admin.site.register(Chihuahua)
admin.site.register(Coahuila)
admin.site.register(Colima)
admin.site.register(CiudadDeMexico)
admin.site.register(Durango)
admin.site.register(Guanajuato)
admin.site.register(Guerrero)
admin.site.register(Hidalgo)
admin.site.register(Jalisco)
admin.site.register(EstadoDeMexico)
admin.site.register(Michoacan)
admin.site.register(Morelos)
admin.site.register(Nayarit)
admin.site.register(NuevoLeon)
admin.site.register(Oaxaca)
admin.site.register(Puebla)
admin.site.register(Queretaro)
admin.site.register(QuintanaRoo)
admin.site.register(SanLuisPotosi)
admin.site.register(Sinaloa)
admin.site.register(Sonora)
admin.site.register(Tabasco)
admin.site.register(Tamaulipas)
admin.site.register(Tlaxcala)
admin.site.register(Veracruz)
admin.site.register(Yucatán)
admin.site.register(Zacatecas)